// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0QMWR_hcTC-ZmBYl96zero5YjPFIXcJ0',
    appId: '1:346495301774:web:8a7af1badb6f37a14171df',
    messagingSenderId: '346495301774',
    projectId: 'lostfoundiiitdmj0',
    authDomain: 'lostfoundiiitdmj0.firebaseapp.com',
    databaseURL: 'https://lostfoundiiitdmj0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lostfoundiiitdmj0.appspot.com',
    measurementId: 'G-1RNRT2QY6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB7QrDLYkRl4ighpscuupFkx5U_8WRRYY',
    appId: '1:346495301774:android:9eb3e52d29e996644171df',
    messagingSenderId: '346495301774',
    projectId: 'lostfoundiiitdmj0',
    databaseURL: 'https://lostfoundiiitdmj0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lostfoundiiitdmj0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjZ5apf38aAMlmyIFYMW2Wsxw6g5zI4K0',
    appId: '1:346495301774:ios:4521c0622868bcd94171df',
    messagingSenderId: '346495301774',
    projectId: 'lostfoundiiitdmj0',
    databaseURL: 'https://lostfoundiiitdmj0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lostfoundiiitdmj0.appspot.com',
    iosClientId: '346495301774-fs1av8q1clo875opdvmo4948bs9dlch2.apps.googleusercontent.com',
    iosBundleId: 'com.iiitdmj.lnf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjZ5apf38aAMlmyIFYMW2Wsxw6g5zI4K0',
    appId: '1:346495301774:ios:0f6b3de4fcf3b7df4171df',
    messagingSenderId: '346495301774',
    projectId: 'lostfoundiiitdmj0',
    databaseURL: 'https://lostfoundiiitdmj0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lostfoundiiitdmj0.appspot.com',
    iosClientId: '346495301774-s8bvei8vf6u3g8ihrdhgoituj87fgdlc.apps.googleusercontent.com',
    iosBundleId: 'com.iiitdmj.lnf.RunnerTests',
  );
}
